---
title: "wos1144"
author: "Guy Mercer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(drc)

# 21 day ai
ai_21_day <- read.csv("output/21_day_ai.csv", header = FALSE)

colnames(ai_21_day) <- c("dose", "percent", "alive", "total")

ai_21_day$dose <- as.numeric(ai_21_day$dose)

ai_21_day$alive <- as.numeric(ai_21_day$alive)

ai_21_day$total <- as.numeric(ai_21_day$total)


ai_21_day_mod <- drm(alive/total ~ dose, data = ai_21_day, fct = LL.3(), weights = total, type = "binomial")

plot(ai_21_day_mod)

summary(ai_21_day_mod)

ED(ai_21_day_mod, respLev = c(50), level = 0.95)

# 21 day form
form_21_day <- read.csv("output/21_day_form.csv", header = FALSE)

colnames(form_21_day) <- c("dose", "percent", "alive", "total")

form_21_day$dose <- as.numeric(form_21_day$dose)

form_21_day$alive <- as.numeric(form_21_day$alive)

form_21_day$total <- as.numeric(form_21_day$total)

form_21_day_mod <- drm(alive/total ~ dose, data = form_21_day, fct = LL.3(), weights = total, type = "binomial")

plot(form_21_day_mod)

summary(form_21_day_mod)

ED(form_21_day_mod, respLev = c(50), level = 0.95)
```

For the 6 day data

```{r}
# 6 day ai
ai_6_day <- read.csv("output/6_day_ai.csv", header = FALSE)

colnames(ai_6_day) <- c("dose", "percent", "alive", "total")

ai_6_day_mod <- drm(alive/total ~ dose, data = ai_6_day, fct = LL.3(), weights = total, type = "binomial")

plot(ai_6_day_mod)

summary(ai_6_day_mod)

ED(ai_6_day_mod, respLev = c(50), level = 0.95)

# 6 day form
form_6_day <- read.csv("output/6_day_form.csv", header = FALSE)

colnames(form_6_day) <- c("dose", "percent", "alive", "total")

form_6_day_mod <- drm(alive/total ~ dose, data = form_6_day, fct = LL.3(), weights = total, type = "binomial")

plot(form_6_day_mod)

summary(form_6_day_mod)

ED(form_6_day_mod, respLev = c(50), level = 0.95)
```

earthworm dataset in drc has multiple replicates for each concentration point and binomial data. On page 100 of the manual they use the weights function with this type of data. Copied below.

```{r}
data("earthworms")

###Examplewithquantaldata 
##Fittinginitialtwo-parameterlog-logisticmodel 
earthworms.m1<-drm(number/total~dose,weights=total, data=earthworms,fct=LL.2(),type="binomial")

summary(earthworms.m1)
```

