---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

Import

```{r}
search_terms <- read.csv("./input/common_search_terms.csv")
```

Combine columns 2-11

```{r}
library(tidyverse)

search_terms_no_title <- search_terms [, -1]

combined_term <- tibble()

for (i in 1:nrow(search_terms_no_title)) {
  
  combined <- paste(search_terms_no_title [i, ], collapse = " ")
  
  combined_term [i, 1] <- search_terms [i, 1]
  
  combined_term [i, 2] <- combined
  
}

colnames(combined_term) <- c("title", "search_terms")

combined_term$search_terms <- gsub(pattern = "[[:space:]]{1,}$", replacement = "", x = combined_term$search_terms)
```

Which combination of search terms returns the most papers?

```{r}
combined_term <- combined_term [grep(pattern = "toxic|effect|mortal|viab|endpoint|end point|oxid|cell cycle|dna damage|apop|necro|sensitiv|growth|surv|aberra|health",
                                             x = combined_term$search_terms,
                                             ignore.case = TRUE),]

# lost 1 paper
combined_term <- combined_term [grep(pattern = "pesti|herbi|insecti|fungi|acari|agrochem",
                                             x = combined_term$search_terms,
                                             ignore.case = TRUE),]
# 1 paper lost. I think this approach strikes the right balance
combined_term <- combined_term [grep(pattern = "co-formulant|formulation|adjuvant|by-product|commercial product|inactive ingredient|inert|formulant|safener|additive|surfactant|solvent|component|commercial form|commercial mixture|formulated|active ingredient|fundamental substance|reagent grade|technical|active principle|active substance|pure|technical grade|technical-grade|alone|active component|pure compound|grade|active constituent|active|active pesticide|active agent",
                                             x = combined_term$search_terms,
                                             ignore.case = TRUE),]

```

